### ISSUE TITLE
Handle when the RPC server is unavailable

### ISSUE THREAD

**Issue by relue2718** [relue2718/onenote-duplicates-remover#7]
Behavior:
The host process got terminated and the tool was unable to retrieve the content.

Guessing:
Version issue? Or due to some anti-virus protection? :(

The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
   at Microsoft.Office.Interop.OneNote.IApplication.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)

The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at Microsoft.Office.Interop.OneNote.IApplication.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)

**Comment by relue2718** [comment]
Check the program's dependency on Windows services.
